### ISSUE TITLE
Setup AppVeyor integration

### ISSUE THREAD

**Issue by Bounz** [Bounz/HomeGenie-BE#1]
Use PR https://github.com/genielabs/HomeGenie/pull/326 from @davidwallis3101.

**Comment by Bounz** [comment]
Hi, @davidwallis3101.
Just noted that `wpkg` packages `.deb` file with errors. Take a look at https://github.com/Bounz/HomeGenie-BE/releases/download/V1.1.15/homegenie_1.1.15_all.deb from `V1.1.15` release. 6 pictures from different locations from `html` folder were packaged to the root of the `.deb` file. Here is screenshot with example that these files were extracted to the root of file system on my Pi:
![image](https://user-images.githubusercontent.com/3062744/35242175-e3e5827e-ffc9-11e7-95fc-7906499fc47e.png)
Do you have any idea what happened and how could we fix it?

**Comment by davidwallis3101** [comment]
odd.. will have a look into it...
