### ISSUE TITLE
Replace external libraries with their NuGet equivalents

### ISSUE THREAD

**Issue by Bounz** [Bounz/HomeGenie-BE#33]
Replace external libraries with their NuGet equivalents.

**Comment by davidwallis3101** [comment]
could do with a mig nuget package still for interfaces to be able to target as I am still referencing the hg one..

**Comment by Bounz** [comment]
@davidwallis3101 What do you mean?
We can create and publish our own package with MIG interface, that should be implemented in interface implementations.

**Comment by davidwallis3101** [comment]
@davidwallis3101 What do you mean?
We can create and publish our own package with MIG interface, that should be implemented in interface implementations - that's what I mean - currently my interface projects are targeting the old MIG dll's but would be nice to do via nuget - or whether a DI framework would remove this dependency? (not done enough with them to know)

**Comment by Bounz** [comment]
>or whether a DI framework would remove this dependency?
No, DI frameworks will not help, because we need to share this interface with others writing custom MIG interfaces. We will need to create our own nuget package, but I prefer not to hurry here because this interface might be refactored.
