### ISSUE TITLE
master branch wont run

### ISSUE THREAD

**Issue by davidwallis3101** [Bounz/HomeGenie-BE#69]
@Bounz 

Just trying to look at the interface issue and just grabbed code from Master and try running but getting the following error on mine:

![image](https://user-images.githubusercontent.com/13855486/40941741-cc3e2300-6843-11e8-9a22-342eed1b6d2d.png)

Known issue?

**Comment by davidwallis3101** [comment]
However 1.1.17 works, have we checked in breaking changes or a broken build into master :o

**Comment by Bounz** [comment]
Yes, as I started committing directly to master (because of trunk-based development) + I needed to synchronize repository between my 2 working places, I had to commit and push non-working solution.
Not nice, I know.

**Comment by davidwallis3101** [comment]
Understood.
