### ISSUE TITLE
Change links and titles in UI

### ISSUE THREAD

**Issue by Bounz** [Bounz/HomeGenie-BE#9]
Change links to the forum and GitHub in web UI.
Also, manage to use another repository for Update Checking and Package Management.

**Comment by Bounz** [comment]
No, but we need to check that update manager and the package manager will work correctly with other repositories. I planned to use mine GitHub forks of Gene's repositories as a source.
Also please do all stuff in a separate branch named "HGBE-9" forked from branch "V1.1.15".

**Comment by davidwallis3101** [comment]
Will do :) - should be able to rename the branch I have :)

**Comment by davidwallis3101** [comment]
what do you want to do with things like:
http://genielabs.github.io/HomeGenie/about.html

**Comment by davidwallis3101** [comment]
I've pushed a branch - can you give me access to appveyor so I can view the builds?

Also can you drop me a mail at david@wallis2000.co.uk so I can send you a message :)

**Comment by Bounz** [comment]
> what do you want to do with things like:
http://genielabs.github.io/HomeGenie/about.html

Let's change it to https://bounz.github.io/HomeGenie-BE/about.html

I'll look at AppVeyor's permissions settings, but I've configured it to build only PR's, version branches and the master branch.

**Comment by Bounz** [comment]
So to trigger a build simply create a new PR from HGBE-9 to V1.1.15.

**Comment by davidwallis3101** [comment]
doesnt look like that triggered it.

**Comment by Bounz** [comment]
It's because you've created PR from `HGBE-9` (this repository) to `master` (this repository) instead of `HGBE-9` (your repository) to `V1.1.15` (this repository).
And build for PR has been triggered (https://ci.appveyor.com/project/Bounz/homegenie-be/build/1.1.15-axrpcsde), as I can see.

**Comment by davidwallis3101** [comment]
ffs - Ill get the hang of git eventually.

**Comment by Bounz** [comment]
Are you going to fix it? 😉

**Comment by Bounz** [comment]
Unexpected reference to deleted file 😄 .
```
Error on line 191 in c:\projects\HomeGenie\HomeGenie_Windows\Packager\setup.iss: Source file "c:\projects\HomeGenie\HomeGenie_Windows\Packager\..\..\HomeGenie\bin\Debug\README.TXT" does not exist.
Compile aborted.
Command exited with code 2
```
